const specialists = [
  {
    id: 1,
    name: "Floripa Delivery",
    services: "Домашний творог, торты, десерты",
    description: "Мы — семья из России, которая проживает в Бразилии уже больше года. Мы, как никто, понимаем, что в эмиграции скучаешь по родным вкусам, поэтому решили организовать доставку десертов, приготовленных нами с любовью по проверенным семейным рецептам, некоторые из которых перешли к нам от наших родителей и даже бабушек. Каждое блюдо мы готовим, как для себя любимых, поэтому мы не экономим на продуктах и выбираем только самое лучшее и свежее!",
    price: [
      { name: "Творог (1 кг)", price: 70 },
      { name: "Сырники (1 кг)", price: 100 },
      { name: "Торт Медовик (1,6 кг)", price: 190 },
      { name: "Торт Наполеон (1,8 кг)", price: 190 },
      { name: "Королевская ватрушка (1,4 кг)", price: 150 },
      { name: "Птичье молоко (500 г)", price: 70 },
      { name: "Яблочная пастила (500 г)", price: 65 },
    ],
    address: "Ingleses Norte",
    telegramChannel: "https://t.me/Olga_Makey",
    website: "https://sweetfloripa.com/",
    instagram: "https://www.instagram.com/floripa_delivery?igsh=NDRyYzg3MTM3Zmpx",
    contact: "+5548991551466",
    photos: [
      "/images/floripa-delivery/floripa-delivery-1.png",
      "/images/floripa-delivery/floripa-delivery-1.jpg",
      "/images/floripa-delivery/floripa-delivery-3.jpg",
    ],
    tags: ["Еда"],
  },
  {
    id: 2,
    name: "Caruta",
    services: "Панамы и корсеты",
    description: "Caruta - это бренд женской одежды. Все началось с пошива одной панамы, она получилась настолько удобной и красивой, что магазин образовался сам собой. Наша особенность - натуральные ткани и индивидуальный пошив по вашим меркам",
    price: [
      { name: "Панама", price: 270 },
      { name: "Корсет от", price: 500 },
    ],
    address: "Florianópolis",
    telegramChannel: "https://t.me/dr_dogova",
    website: "",
    instagram: "https://www.instagram.com/pure_sew?igsh=YzY5bWh1bTc5N201&utm_source=qr",
    contact: "",
    photos: [
      "/images/caruta/caruta-1.jpeg",
      "/images/caruta/caruta-2.jpeg",
      "/images/caruta/caruta-3.jpeg",
    ],
    tags: ["Красота", "Другое", "Одежда"],
  },

  {
    id: 3,
    name: "ИП Калиниченко Юлия Николаевна",
    services: "Доставка грузов и документов по РФ со скидкой до 60%",
    description: "Мы Транспортная компания СДЭК . Заключив с нами договор ,вы получаете менеджера по сопровождению и скидки на отправки до 60% ",
    price: [],
    address: "РФ",
    telegramChannel: "https://t.me/79054403334",
    website: "",
    instagram: "",
    contact: "+79054403334",
    photos: [
      "/images/yulia-kalinichenko/yulia-kalinichenko-1.png",
    ],
    tags: ["Доставка"],
  },
  {
    id: 4,
    name: "Флорипа доставка еды  Ирина",
    services: "Еда на заказ",
    description: "Замороженные полуфабрикаты, кейтеринг, услуги повара ",
    price: [
      { name: "Пельмени говядина и свинина, 950 г", price: 95 },
      { name: "Пельмени куриные, 950 г", price: 85 },
      { name: "Хинкали, 600 г", price: 60 },
      { name: "Гедза с креветками и пекинской капустой, 600 г", price: 75 },
      { name: "Вареники с картошкой и луком, 950 г", price: 60 },
      { name: "Вареники с картошкой и лесными грибами, 950 г", price: 75 },
      { name: "Котлеты куриные, 600 г", price: 40 },
      { name: "Котлеты из свинины и говядины, 600 г", price: 45 },
      { name: "Котлеты говяжьи, 600 г", price: 50 },
      { name: "Котлеты рыбные, 600 г", price: 90 },
      { name: "Фрикадельки (по мотивам IKEA), 450 г", price: 40 },
      { name: "Люля-кебаб, 600 г", price: 55 },
      { name: "Куриные отбивные, 600 г (3 шт)", price: 50 },
      { name: "Чебуреки, 6 шт", price: 40 },
    ],
    address: "Cachoeira do bom Jesus , Florianopolis",
    telegramChannel: "https://t.me/povarfloripadostavka",
    website: "",
    instagram: "",
    contact: "+5541991611252",
    photos: [
      "/images/povar-irina/povar-irina-1.jpeg",
      "/images/povar-irina/povar-irina-2.jpeg",
      "/images/povar-irina/povar-irina-3.jpeg",
    ],
    tags: ["Еда"],
  },
  {
    id: 5,
    name: "Юлия",
    services: "Финансовый советник (фондовый и крипто рынок), игра CashFlow",
    description: "Работа на повышение финансовой грамотности, составление личного финансового плана и подбор инструментов под цели и задачи каждого клиента. Есть опыт ведения бизнеса в Бразилии, работа с трудовыми договорами, банками, бухгалтерами, адвокатами и судебными процессами. ",
    price: [],
    address: "Florianopolis",
    telegramChannel: "https://t.me/marchenkoprava",
    website: "",
    instagram: "https://www.instagram.com/marchenko.prava?igsh=N25kMHprcjM3eTIw",
    contact: "+5548991223112",
    photos: [
      "/images/yulia-marchenko/yulia-marchenko-1.jpg",
    ],
    tags: ["Документы", "Бизнес"],
  },
  {
    id: 6,
    name: "Ольга Макейкина",
    services: "Разработка и дизайн сайтов",
    description: "Я — Ольга, веб-разработчик. Создаю сайты «под ключ» — от идеи и дизайна до финального запуска. Разрабатываю удобные, адаптивные и быстрые сайты, которые корректно работают на всех устройствах. Дорабатываю и поддерживаю уже существующие проекты, исправляю ошибки, добавляю новый функционал. Могу интегрировать платежные системы, подключить формы обратной связи, настроить анимации и динамические элементы. Забочусь о том, чтобы сайт был не только красивым, но и удобным для пользователей. Готова к сотрудничеству! Цены по запросу, зависят от сложности и объема проекта.",
    price: [
      { name: "Лендинг от", price: 1000 },
    ],
    address: "Florianopolis",
    telegramChannel: "https://t.me/Olga_Makey",
    website: "https://olgamakeikina.netlify.app/",
    instagram: "https://www.instagram.com/olgamakeykina?igsh=MWpldXB4MW56MnB6cw==",
    contact: "+5548991551466",
    photos: [
      "/images/olga-makeikina/olga-makeikina-1.jpg",
    ],
    tags: ["IT"],
  },
  {
    id: 7,
    name: "Элеанор",
    services: "Домашний творог",
    description: "Делаю вкусный домашний творог.",
    price: [
      { name: "Творог, 500 г", price: 27 },
      { name: "Творог, 1000 г", price: 54 },
    ],
    address: "Florianópolis (ingleses)",
    telegramChannel: "https://t.me/capiva_ra",
    website: "",
    instagram: "",
    contact: "+554891523145",
    photos: [
      "/images/eleanor/eleanor-1.jpg",
      "/images/eleanor/eleanor-2.jpg",
    ],
    tags: ["Еда"],
  },
  {
    id: 8,
    name: "Blinopolis",
    services: "Блинная",
    description: "Если соскучились по настоящим русским блинам, то приходите в гости! Сладкие блины, блины с начинками и черный чай ждут вас!",
    price: [
      { name: "Блины в ассортименте от", price: 18 },
    ],
    address: "Rod. João Gualberto Soares, 56 - quiosque 1 - Ingleses do Rio Vermelho, Florianópolis - SC, 88058-300",
    telegramChannel: "",
    website: "",
    instagram: "",
    contact: "",
    photos: [
      "/images/blinopolis/blinopolis.png",
    ],
    tags: ["Еда"],
  },
  {
    id: 9,
    name: "PRO IT LTDA",
    services: "Обмен валют",
    description: "Обмен валют и криптовалют на реалы, баты, гривны и др.",
    price: [],
    address: "Florianópolis",
    telegramChannel: "https://t.me/obmen_money",
    website: "",
    instagram: "",
    contact: "+5548991516988",
    photos: [
      "/images/obmen-money/obmen-money.jpg",
    ],
    tags: ["IT", "Деньги", "Недвижимость"],
  },
  {
    id: 10,
    name: `Rentcar "Carro4you"`,
    services: "Аренда автомобилей, выкуп автомобилей, продажа в рассрочку",
    description: "Carro4you официальная компания. Наши принципы: - прозрачность и легальность нашей деятельности, - комфортные автомобили по доступным ценам, - отсутствие бюрократии, - гибкая система оплаты(рубли, реалы, доллары, евро, usdt). Самый низкий залог среди конкурентов. Мы регулярно обновляем свой автопарк и следим за техническим состоянием наших машин.",
    price: [
      { name: "Аренда удобных автомобилей от", price: 84 },
    ],
    address: "Florianópolis, Ingléses, Servidão José Manoel Pacífico 161",
    telegramChannel: "https://t.me/carro4you",
    website: "https://www.carro4you.com/",
    instagram: "https://www.instagram.com/carro4you_br?igsh=MTRhemp3NWN1cjU4MQ==",
    contact: "+5548996818468",
    photos: [
      "/images/car4you/car4you.png",
    ],
    tags: ["Авто"],
  },
  {
    id: 11,
    name: `Юрий`,
    services: "Услуги асадора, мангал-мастер",
    description: "Помогу с приготовлением шураско (мясо, рыба, птица и овощи), рассчитаю объем продуктов, помогу с закупкой и доставкой.",
    price: [
      { name: "Услуги асадора в час", price: 50 },
    ],
    address: "Florianópolis",
    telegramChannel: "https://t.me/eat_meat_floripa",
    website: "",
    instagram: "",
    contact: "+5511974362834",
    photos: [
      "/images/yury/yury.jpg",
    ],
    tags: ["Еда"],
  },
  {
    id: 12,
    name: `Irina`,
    services: "Комбинированный маникюр и педикюр, работа со сложными стопами",
    description: "Мастер ногтевого сервиса (маникюр/педикюр)",
    price: [
      { name: "Маникюр", price: 100 },
      { name: "Педикюр от", price: 140 },
    ],
    address: "R. Brisamar, 191 - Ingleses Norte, Florianópolis - SC, 88058-570",
    telegramChannel: "https://t.me/irina_metso",
    website: "",
    instagram: "https://www.instagram.com/irina_metso_nails/?igsh=ZWN6eTFuZzZseThk#",
    contact: "+5548988097570",
    photos: [
      "/images/irina-metso/irina-metso-1.jpg",
      "/images/irina-metso/irina-metso-2.jpg",
      "/images/irina-metso/irina-metso-3.png",
    ],
    tags: ["Красота"],
  },
  {
    id: 13,
    name: `Time315 investimentos`,
    services: "Обмен usdt, руб., на бразильский реал.",
    description: "Оплачиваем автомобили и недвижимость от вашего имени. Содействие в получении ВНЖ через инвестиции. Мы занимаемся обменом с 2020 года — надёжно, конфиденциально и с индивидуальным подходом. Имеем собственные пункты приёма наличных в десятках стран и сотнях городов по всему миру.",
    price: [
      { name: "Комиссия 2% от спот рынка usdt/brl (Binance)", price: 0 },
    ],
    address: "Флорианополис",
    telegramChannel: "https://t.me/Time315",
    website: "https://time315.pro/",
    instagram: "",
    contact: "+79233157315",
    photos: [
      "/images/time315/time315.jpg",
    ],
    tags: ["Деньги", "Другое"],
  },
  {
    id: 14,
    name: `Dom Brazil Real Estate Investment`,
    services: "Малоэтажное строительство и девелопмент. Агентские услуги по недвижимости",
    description: "Мы — русскоговорящая строительная компания, работающая во Флорианополисе (Бразилия), специализирующаяся на малоэтажном строительстве и инвестиционных проектах. Наша команда — это профессионалы с международным опытом, которые знают, как важно сочетание качества, надёжности и прозрачности при строительстве за рубежом. Мы сопровождаем клиентов на всех этапах — от подбора участка и проектирования до строительства и сдачи объекта «под ключ». Мы строим: жилые дома и виллы; малоэтажные комплексы и таунхаусы; проекты под аренду и инвестиции. Что нас отличает: - Полное сопровождение на русском языке. - Современные технологии и качественные материалы. - Помощь в получении ВНЖ через инвестиции в недвижимость. - Работаем исключительно в одном из самых стабильных и растущих регионов Бразилии — Санта-Катарине. Мы предлагаем клиентам готовые решения и индивидуальный подход. С нами процесс строительства и инвестиций становится простым и безопасным. Оставьте Вашу заявку, и наш специалист свяжется с Вами в ближайшее время!",
    price: [
    ],
    address: "Servidão Três Marias, 553 - Ingleses, Florianópolis - SC, 88058-648",
    telegramChannel: "https://t.me/+_rolsmvxwIs0ODMy",
    website: "https://investdombrazil.com/",
    instagram: "https://www.instagram.com/kbievskikh?igsh=ZWI2YzEzYmMxYg==",
    contact: "+5548988117424",
    photos: [
      "/images/dombrazil/dombrazil-1.png",
      "/images/dombrazil/dombrazil-2.jpg",
      "/images/dombrazil/dombrazil-3.png",
    ],
    tags: ["Бизнес", "Недвижимость"],
  },
  {
    id: 15,
    name: `Елена Трапезникова`,
    services: "Логопед, очные и онлайн занятия логопедические, обучение чтению онлайн/очно",
    description: "Логопед с опытом работы 10 лет. Очный опыт с 2015г. Онлайн с 2020 года. Работа с билингвальными детьми, русский как иностранный для детей, у которых преобладает язык окружающей среды.  Работа с лексикой/грамматикой/звукопроизношением и письменной речью. Работа с неговорящими детьми/детьми с задержкой речевого развития. Длительность занятия 30 минут (логопедическое) и 40 минут (обучение чтению).",
    price: [
      { name: "ОЧНОЕ логопедическое занятие разовое", price: 100 },
      { name: "ОЧНОЕ логопедическое занятие  в абонементе (8 занятий/месяц), цена за занятие", price: 90 },
      { name: "ОНЛАЙН логопедическое занятие разовое", price: 80 },
      { name: "ОНЛАЙН логопедическое занятие  в абонементе (8 занятий/месяц), цена за занятие", price: 70 },
    ],
    address: "Rua Recanto do Sol, 469 - Ingleses, Florianópolis - SC",
    telegramChannel: "https://t.me/elena_belena",
    website: "",
    instagram: "",
    contact: "+5547936184509",
    photos: [
      "/images/elena-trapeznikova/elena-trapeznikova.jpeg"
    ],
    tags: ["Дети"],
  },
  {
    id: 16,
    name: `Anushka`,
    services: "Одежда из муслина",
    description: "Муслиновая одежда 100 %хлопка: -детская, -женская, -мужская. Пеленки, детские панамки,трусики",
    price: [
    ],
    address: "Флорианополис - доставка по острову",
    telegramChannel: "https://t.me/valova_anna",
    website: "",
    instagram: "http://instagram.com/anushka.clothing",
    contact: "+5548992084041",
    photos: [
      "/images/anushka/anushka-1.jpeg",
      "/images/anushka/anushka-2.jpeg",
      "/images/anushka/anushka-3.jpeg",
    ],
    tags: ["Одежда"],
  },
];

export default specialists;
