const specialists = [
  {
    id: 1,
    name: "Floripa Delivery",
    services: "Домашний творог, торты, десерты",
    description: "Мы — семья из России, которая проживает в Бразилии уже больше года. Мы, как никто, понимаем, что в эмиграции скучаешь по родным вкусам, поэтому решили организовать доставку десертов, приготовленных нами с любовью по проверенным семейным рецептам, некоторые из которых перешли к нам от наших родителей и даже бабушек. Каждое блюдо мы готовим, как для себя любимых, поэтому мы не экономим на продуктах и выбираем только самое лучшее и свежее!",
    price: [
      { name: "Творог (1 кг)", price: 70 },
      { name: "Сырники (1 кг)", price: 100 },
      { name: "Торт Медовик (1,6 кг)", price: 190 },
      { name: "Торт Наполеон (1,8 кг)", price: 190 },
      { name: "Королевская ватрушка (1,4 кг)", price: 150 },
      { name: "Птичье молоко (500 г)", price: 70 },
      { name: "Яблочная пастила (500 г)", price: 65 },
    ],
    address: "Ingleses Norte",
    telegramChannel: "https://t.me/Olga_Makey",
    website: "https://sweetfloripa.com/",
    instagram: "https://www.instagram.com/floripa_delivery?igsh=NDRyYzg3MTM3Zmpx",
    contact: "+5548991551466",
    photos: [
      "/images/floripa-delivery/floripa-delivery-1.png",
      "/images/floripa-delivery/floripa-delivery-1.jpg",
      "/images/floripa-delivery/floripa-delivery-3.jpg",
    ],
    tags: ["Еда"],
  },
  {
    id: 2,
    name: "Caruta",
    services: "Панамы и корсеты",
    description: "Caruta - это бренд женской одежды. Все началось с пошива одной панамы, она получилась настолько удобной и красивой, что магазин образовался сам собой. Наша особенность - натуральные ткани и индивидуальный пошив по вашим меркам",
    price: [
      { name: "Панама", price: 270 },
      { name: "Корсет от", price: 500 },
    ],
    address: "Florianópolis",
    telegramChannel: "https://t.me/dr_dogova",
    website: "",
    instagram: "https://www.instagram.com/pure_sew?igsh=YzY5bWh1bTc5N201&utm_source=qr",
    contact: "",
    photos: [
      "/images/caruta/caruta-1.jpeg",
      "/images/caruta/caruta-2.jpeg",
      "/images/caruta/caruta-3.jpeg",
    ],
    tags: ["Красота", "Другое", "Одежда"],
  },

  {
    id: 3,
    name: "ИП Калиниченко Юлия Николаевна",
    services: "Доставка грузов и документов по РФ со скидкой до 60%",
    description: "Мы Транспортная компания СДЭК . Заключив с нами договор ,вы получаете менеджера по сопровождению и скидки на отправки до 60% ",
    price: [],
    address: "РФ",
    telegramChannel: "https://t.me/79054403334",
    website: "",
    instagram: "",
    contact: "+79054403334",
    photos: [
      "/images/yulia-kalinichenko/yulia-kalinichenko-1.png",
    ],
    tags: ["Доставка"],
  },
  {
    id: 4,
    name: "Флорипа доставка еды  Ирина",
    services: "Еда на заказ",
    description: "Замороженные полуфабрикаты, кейтеринг, услуги повара ",
    price: [
  { name: "Котлеты из куриного филе, 600 г", price: 40 },
  { name: "Котлеты из говядины, 600 г", price: 50 },
  { name: "Котлеты из говядины и свинины, 600 г", price: 45 },
  { name: "Котлеты из лосося и хека, 600 г", price: 90 },
  { name: "Фрикадельки по рецепту Икеа, 450 г", price: 40 },
  { name: "Пельмени, 950 г", price: 95 },
  { name: "Пельмени/равиоли с курицей и зеленью, 950 г", price: 85 },
  { name: "Вареники с картошкой, 950 г", price: 60 },
  { name: "Вареники с картофелем и сушеными грибами, 950 г", price: 75 },
  { name: "Хинкали, 600 г (около 10 штук)", price: 65 },
  { name: "Чебуреки с говядиной, 6 шт", price: 40 },
    ],
    address: "Cachoeira do bom Jesus , Florianopolis",
    telegramChannel: "https://t.me/povarfloripadostavka",
    website: "",
    instagram: "",
    contact: "+79500175047",
    photos: [
      "/images/povar-irina/povar-irina-1.jpeg",
      "/images/povar-irina/povar-irina-2.jpeg",
      "/images/povar-irina/povar-irina-3.jpeg",
    ],
    tags: ["Еда"],
  },
  {
    id: 5,
    name: "Юлия",
    services: "Финансовый советник (фондовый и крипто рынок), игра CashFlow",
    description: "Работа на повышение финансовой грамотности, составление личного финансового плана и подбор инструментов под цели и задачи каждого клиента. Есть опыт ведения бизнеса в Бразилии, работа с трудовыми договорами, банками, бухгалтерами, адвокатами и судебными процессами. ",
    price: [],
    address: "Florianopolis",
    telegramChannel: "https://t.me/marchenkoprava",
    website: "",
    instagram: "https://www.instagram.com/marchenko.prava?igsh=N25kMHprcjM3eTIw",
    contact: "+5548991223112",
    photos: [
      "/images/yulia-marchenko/yulia-marchenko-1.jpg",
    ],
    tags: ["Документы", "Бизнес"],
  },
  {
    id: 6,
    name: "Ольга Макейкина",
    services: "Разработка и дизайн сайтов",
    description: "Я — Ольга, веб-разработчик. Создаю сайты «под ключ» — от идеи и дизайна до финального запуска. Разрабатываю удобные, адаптивные и быстрые сайты, которые корректно работают на всех устройствах. Дорабатываю и поддерживаю уже существующие проекты, исправляю ошибки, добавляю новый функционал. Могу интегрировать платежные системы, подключить формы обратной связи, настроить анимации и динамические элементы. Забочусь о том, чтобы сайт был не только красивым, но и удобным для пользователей. Готова к сотрудничеству! Цены по запросу, зависят от сложности и объема проекта.",
    price: [
      { name: "Лендинг от", price: 1000 },
    ],
    address: "Florianopolis",
    telegramChannel: "https://t.me/Olga_Makey",
    website: "https://olgamakeikina.netlify.app/",
    instagram: "https://www.instagram.com/olgamakeykina?igsh=MWpldXB4MW56MnB6cw==",
    contact: "+5548991551466",
    photos: [
      "/images/olga-makeikina/olga-makeikina-1.jpg",
    ],
    tags: ["IT"],
  },
  {
    id: 7,
    name: "Элеанор",
    services: "Домашний творог",
    description: "Делаю вкусный домашний творог.",
    price: [
      { name: "Творог, 500 г", price: 27 },
      { name: "Творог, 1000 г", price: 54 },
    ],
    address: "Florianópolis (ingleses)",
    telegramChannel: "https://t.me/capiva_ra",
    website: "",
    instagram: "",
    contact: "+554891523145",
    photos: [
      "/images/eleanor/eleanor-1.jpg",
      "/images/eleanor/eleanor-2.jpg",
    ],
    tags: ["Еда"],
  },
  {
    id: 8,
    name: "Blinopolis",
    services: "Блинная",
    description: "Если соскучились по настоящим русским блинам, то приходите в гости! Сладкие блины, блины с начинками и черный чай ждут вас!",
    price: [
      { name: "Блины в ассортименте от", price: 18 },
    ],
    address: "Rod. João Gualberto Soares, 56 - quiosque 1 - Ingleses do Rio Vermelho, Florianópolis - SC, 88058-300",
    telegramChannel: "",
    website: "",
    instagram: "",
    contact: "",
    photos: [
      "/images/blinopolis/blinopolis.png",
    ],
    tags: ["Еда"],
  },
  {
    id: 9,
    name: "PRO IT LTDA",
    services: "Обмен валют",
    description: "Обмен валют и криптовалют на реалы, баты, гривны и др.",
    price: [],
    address: "Florianópolis",
    telegramChannel: "https://t.me/obmen_money",
    website: "",
    instagram: "",
    contact: "+5548991516988",
    photos: [
      "/images/obmen-money/obmen-money.jpg",
    ],
    tags: ["IT", "Деньги", "Недвижимость"],
  },
  {
    id: 10,
    name: `Rentcar "Carro4you"`,
    services: "Аренда автомобилей, выкуп автомобилей, продажа в рассрочку",
    description: "Carro4you официальная компания. Наши принципы: - прозрачность и легальность нашей деятельности, - комфортные автомобили по доступным ценам, - отсутствие бюрократии, - гибкая система оплаты(рубли, реалы, доллары, евро, usdt). Самый низкий залог среди конкурентов. Мы регулярно обновляем свой автопарк и следим за техническим состоянием наших машин.",
    price: [
      { name: "Аренда удобных автомобилей от", price: 84 },
    ],
    address: "Florianópolis, Ingléses, Servidão José Manoel Pacífico 161",
    telegramChannel: "https://t.me/carro4you",
    website: "https://www.carro4you.com/",
    instagram: "https://www.instagram.com/carro4you_br?igsh=MTRhemp3NWN1cjU4MQ==",
    contact: "+5548996818468",
    photos: [
      "/images/car4you/car4you.png",
    ],
    tags: ["Авто"],
  },
  {
    id: 11,
    name: `Юрий`,
    services: "Услуги асадора, мангал-мастер",
    description: "Помогу с приготовлением шураско (мясо, рыба, птица и овощи), рассчитаю объем продуктов, помогу с закупкой и доставкой.",
    price: [
      { name: "Услуги асадора в час", price: 50 },
    ],
    address: "Florianópolis",
    telegramChannel: "https://t.me/eat_meat_floripa",
    website: "",
    instagram: "",
    contact: "+5511974362834",
    photos: [
      "/images/yury/yury.jpg",
    ],
    tags: ["Еда"],
  },
];

export default specialists;
